spring:
  datasource:
    url: ${datasource}
      username: ${username}
      password: ${password}
      driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: ${EMAIL_PORT}
    username: umc.catholic@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 300MB
jwt:
  heaer : Authorization
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds : 3600