spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umcmathingcenter
    username: root
    password: dgandreas125?!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: umc.catholic@gmail.com
    password: filkyhnbhlsjykls
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  redis:
    host: 43.203.93.17
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 300MB
jwt:
  heaer : Authorization
  secret: dW1jLW1hdGNoaW5nLWNlbnRlci1qd3Qtc2VjcmV0LWtleS1pbmNvZGUtdW1jLW1hdGNoaW5nLWNlbnRlci1qd3Qtc2VjcmV0LWtleS1pbmNvZGU=
  token-validity-in-seconds : 86400